---
main_domain: ans.local
repo_server_fqdn: "infra-amont-repo01.{{ main_domain }}"

ntpservers:
  - ntp.ovh.net

allowednets:
  - '10.25.50.0/24'
  - '172.16.41.0/24'

repo_server_ip: 10.25.50.103

alma_repos:
  - baseos
  - appstream
  - extras

repo_base_path: "/var/www/html/repos"

alma_releases:
 - "9"
 - "10"
# liste des alias http pour le serveur repo packages alma, dois correspondre au variables repo_http_alias dans les inventory des alma
repo_http_alias_list:
 - "alma9-repos"
 - "alma10-repos"
