[prod]
localhost ansible_connection=local

[alma10]
infra-prod-repo01
infra-prod-tfansible01
infra-prod-freeipa01
infra-prod-proxy01

[infra_prod]
infra-prod-repo01
infra-prod-tfansible01
infra-prod-freeipa01
infra-prod-proxy01

[cmf]
infra-prod-repo01
infra-prod-tfansible01
infra-prod-freeipa01
infra-prod-proxy01

[ipaservers]
infra-prod-freeipa01

[tfansible]
infra-prod-tfansible01

[repo]
infra-prod-repo01

[proxy]
infra-prod-proxy01
