# Parametres DNS
ipaserver_domain: ans.local
ipaserver_realm: ANS.LOCAL
ipaserver_setup_dns: yes
ipaserver_auto_reverse: yes
ipaserver_forwarders: ['213.186.33.99']

# Configuration Host & IP
ipa_server_fqdn: infra-prod-freeipa01.ans.local
ipa_server_ip: 10.11.90.13
 
# Réseaux pour les zones DNS inverses
ipa_reverse_zones:
  - 10.11.90.0/24
  - 10.11.52.0/24
  - 10.11.70.0/24
  - 10.11.30.0/24

