[prod]
localhost ansible_connection=local

[alma10]
infra-outils-repo01
infra-outils-tfansible01
infra-outils-freeipa01
infra-outils-proxy01

[infra_prod]
infra-outils-repo01
infra-outils-tfansible01
infra-outils-freeipa01
infra-outils-proxy01

[cmf]
infra-outils-repo01
infra-outils-tfansible01
infra-outils-freeipa01
infra-outils-proxy01

[ipaservers]
infra-outils-freeipa01

[tfansible]
infra-outils-tfansible01

[repo]
infra-outils-repo01

[proxy]
infra-outils-proxy01

[squid_servers:children]
proxy
