---
# tasks file for remediation-alma10
- name: Ensure remediation reports directory exists
  ansible.builtin.file:
    path: /var/log/openscap/remediation
    state: directory
    mode: "0755"

- name: Execute OpenSCAP remediation
  ansible.builtin.command:
    cmd: >
      oscap xccdf eval
      --remediate
      --profile {{ openscap_remediation_profile | default('xccdf_org.ssgproject.content_profile_cis_server_l1') }}
      --results /var/log/openscap/remediation/results-remediation-{{ openscap_remediation_profile | regex_replace('^xccdf_org\\.ssgproject\\.content_profile_', '') }}-{{ ansible_hostname }}-{{ ansible_date_time.date }}.xml
      --report /var/log/openscap/remediation/report-remediation-{{ openscap_remediation_profile | regex_replace('^xccdf_org\\.ssgproject\\.content_profile_', '') }}-{{ ansible_hostname }}-{{ ansible_date_time.date }}.html
      --fetch-remote-resources
      /usr/share/xml/scap/ssg/content/ssg-almalinux10-ds.xml
  register: oscap_remediation
  failed_when: oscap_remediation.rc not in [0, 2] # 0 = Compliant, 2 = Non-compliant but command succeeded
  changed_when: true
