- name: Enroll a host in IDM
  hosts: "{{ HOSTS }}:!ipaservers"
  gather_facts: yes
  become: true

  vars_files:
    - ../../vaults/vault_freeipa.yml
    - ../../inventory/prod/group_vars/ipaservers/ipaservers.yml

  tasks:
    - name: "Call role_setup_freeipa_client"
      ansible.builtin.include_role:
        name: "role_setup_freeipa_client"
        tasks_from: main.yml
