- name: Enroll a host in IDM
  hosts: "{{ HOSTS }}"
  gather_facts: yes

  vars_files:
    - ../../vaults/vault_freeipa.yml

  tasks:
    - name: Join host to FreeIPA domain
      ansible.builtin.include_role:
        name: role_setup_freeipa_client
      vars:
        ipa_operation: enroll_ipaclient
        ipa_admin_user: "admin"
        ipa_admin_password: "{{ vault_ipaadmin_password }}"
        ipa_client_fqdn: "{{ ansible_fqdn }}"
        ipa_client_domain: "{{ main_domain }}"
        ipa_client_ip: "{{ ansible_host }}"
