---
# tasks file for installation-openscap
- name: Install OpenSCAP scanner and security guide
  ansible.builtin.dnf:
    name:
      - openscap-scanner
      - scap-security-guide
    state: present
    update_cache: yes
