[prod]
localhost ansible_connection=local

[alma10]
infra-amont-repo01
infra-amont-tfansible01
infra-amont-freeipa01
infra-amont-proxy01

[infra_prod]
infra-amont-repo01
infra-amont-tfansible01
infra-amont-freeipa01
infra-amont-proxy01

[cmf]
infra-amont-repo01
infra-amont-tfansible01
infra-amont-freeipa01
infra-amont-proxy01

[ipaservers]
infra-amont-freeipa01

[tfansible]
infra-amont-tfansible01

[repo]
infra-amont-repo01

[proxy]
infra-amont-proxy01

[squid_servers:children]
proxy
