[amont]
localhost ansible_connection=local

[alma9]
infra-amont-repo01
infra-amont-rebond01
infra-amont-tfansible01
infra-amont-dns01
test01

[infra_amont]
infra-amont-repo01
infra-amont-rebond01
infra-amont-tfansible01
infra-amont-dns01

[cmf]
infra-amont-repo01
infra-amont-rebond01
infra-amont-tfansible01
infra-amont-dns01
test01

[ipaservers]
infra-amont-dns01

[tfansible]
infra-amont-tfansible01

[repo]
infra-amont-repo01

[test_amont]
test01

