---
- name: Supprimer anciennes versions conflictuelles de bind-utils
  ansible.builtin.dnf:
    name:
      - bind-utils
      - bind9.18-utils
    state: absent
  ignore_errors: true

- name: Installer outils Linux essentiels
  ansible.builtin.dnf:
    name:
      - nano
      - vim
      - wget
      - curl
      - git
      - net-tools
      - bind-utils
      - bash-completion
      - htop
      - lsof
      - tcpdump
      - unzip
      - python3
      - python3-pip
      - ncdu
      - policycoreutils-python-utils
      - nmap-ncat
    state: present
    update_cache: true
  register: install_result

- name: Afficher les éventuels échecs de paquets
  ansible.builtin.debug:
    msg: "{{ install_result.failures | default([]) }}"
  when: install_result is failed
