---
- name: Installer outils Linux essentiels
  ansible.builtin.dnf:
    name:
      # Éditeurs
      - nano
      - vim
      # Réseau & diagnostic
      - wget
      - curl
      - net-tools
      - bind-utils
      - tcpdump
      - nmap-ncat
      - traceroute
      - iputils
      # Système & fichiers
      - lsof
      - tar
      - unzip
      - zip
      - rsync
      - tree
      - findutils
      - procps-ng
      - sysstat
      - bash-completion
      # Sécurité & SELinux
      - policycoreutils-python-utils
      - openssl
      # Dev & scripting
      - git
      - python3
      - python3-pip
      - jq
      - make
    state: present
    update_cache: true

