---
# ────────────────────────────────────────────────────────────────────────────
#    Tâches spécifiques aux machines Debian
# ────────────────────────────────────────────────────────────────────────────


- name: "[Debian] Vérifier les mises à jour de sécurité manquantes sur cette machine"
  ansible.builtin.include_role:
    name: checks
    tasks_from: check_updates_deb.yml

- name: "[Debian] Vérifier si un redémarrage est en attente"
  ansible.builtin.include_role:
    name: checks
    tasks_from: check_reboot_deb.yml

- name: "[Debian] Vérifier quand le dernier correctif a été appliqué"
  ansible.builtin.include_role:
    name: checks
    tasks_from: check_patch_history_deb.yml

- name: "[Debian] Vérifier la date du dernier démarrage"
  ansible.builtin.include_role:
    name: checks
    tasks_from: check_last_boot.yml
