---
- name: reload postfix
  become: true
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: restart postfix
  become: true
  ansible.builtin.service:
    name: postfix
    state: restarted
