---
- name: Supprimer l'entree erronee sur 127.0.0.1
  lineinfile:
    path: /etc/hosts
    regexp: ^127\.0\.0\.1\s+infra-amont-tfansible01
    state: absent

- name: Correction du Hostname
  hostname:
    name: "{{ inventory_hostname }}.ans.local"

- name: Configuration propre de /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}.ans.local {{ inventory_hostname }}"
    state: present

- name: Nettoyage des anciens certificats/configs (Force Clean)
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/ipa/ca.crt
    - /etc/ipa/default.conf
    - /etc/krb5.conf

- name: Forcer le DNS vers le serveur IPA
  copy:
    dest: /etc/resolv.conf
    content: |
      nameserver 10.11.90.13
      search ans.local

- name: Install FreeIPA Client
  include_role:
    name: freeipa.ansible_freeipa.ipaclient
  vars:
    ipaadmin_password: "{{ vault_ipaadmin_password }}"
    ipaclient_domain: ans.local
    ipaclient_realm: ANS.LOCAL
    ipaclient_servers: [10.11.90.13]
    ipaclient_mkhomedir: true
    ipaclient_force_join: true
