---
- name: Lire les variables FreeIPA
  ansible.builtin.include_vars:
    file: "../../vaults/vault_freeipa.yml"

- name: Définir le hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname | regex_replace('^infra-prod', 'infra-amont') }}.{{ freeipa_domain }}"

- name: Vérifier le hostname actif
  become: true
  ansible.builtin.command: hostnamectl --static
  register: hostname_result
  changed_when: false

- name: Installer le client FreeIPA
  become: true
  ansible.builtin.package:
    name: freeipa-client
    state: present

- name: Vérifier si déjà enrolé FreeIPA
  ansible.builtin.stat:
    path: /etc/ipa/default.conf
  register: ipa_client_registered

- name: Vérifier variables FreeIPA obligatoires
  ansible.builtin.assert:
    that:
      - freeipa_domain is defined
      - freeipa_realm is defined
      - freeipa_server is defined
      - freeipa_admin_principal is defined
      - freeipa_admin_password is defined
    fail_msg: "Variables FreeIPA manquantes dans vault_freeipa.yml"

- name: Enroller la machine dans FreeIPA
  become: true
  ansible.builtin.command: >
    ipa-client-install
    --unattended
    --force
    --hostname={{ inventory_hostname | regex_replace('^infra-prod', 'infra-amont') }}.{{ freeipa_domain }}
    --domain={{ freeipa_domain }}
    --realm={{ freeipa_realm }}
    --server={{ freeipa_server }}
    --principal={{ freeipa_admin_principal }}
    --password={{ freeipa_admin_password }}
  when: not ipa_client_registered.stat.exists
