---
# Rôle : copy_ssh_key
# Objectif : déployer la clé publique SSH du contrôleur Ansible sur les cibles

- name: "DEBUG - Vérification du chemin de la clé"
  ansible.builtin.debug:
    msg: "Tentative de lecture de la clé : {{ ssh_pub_key_path }} pour l'utilisateur cible : {{ ssh_target_user }}"
  run_once: true

- name: "Installer la clé publique sur l’hôte distant"
  ansible.posix.authorized_key:
    user: "{{ ssh_target_user }}"
    state: present
    key: "{{ lookup('ansible.builtin.file', ssh_pub_key_path) }}"
    exclusive: no
