---
- name: Deploiement du Serveur FreeIPA IDM
  hosts: ipaservers
  become: yes

  collections:
    - ansible.netcommon
    - freeipa.ansible_freeipa

  vars_files:
    - ../../vaults/vault_freeipa.yml

  roles:
    - role_setup_freeipa_server

  environment:
    http_proxy: "http://10.11.70.11:3128"
    https_proxy: "http://10.11.70.11:3128"
