---
- name: Integration des données dans FreeIPA
  hosts: "{{ groups['ipaservers'][0] }}"
  become: yes

  collections:
    - ansible.netcommon
    - freeipa.ansible_freeipa

  vars_files:
    - users_data.yml
    - ../../vaults/vault_freeipa.yml

  tasks:
    - name: Create Groups
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ vault_ipaadmin_password }}"
        name: "{{ item.name }}"
        state: present
      loop: "{{ ipa_groups }}"
    
    - name: Create Users
      freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ vault_ipaadmin_password }}"
        name: "{{ item.name }}"
        first: "{{ item.first }}"
        last: "{{ item.last }}"
        email: "{{ item.email }}"
        password: "{{ item.password }}"
        update_password: "{{ item.update_password | default('on_create') }}"      # ← AJOUT
        passwordexpiration: "{{ item.passwordexpiration | default(omit) }}"  
        state: present
      loop: "{{ ipa_users }}"
      loop_control:
        label: "{{ item.name }}"
    
    - name: Add users to their respective groups
      freeipa.ansible_freeipa.ipagroup:
        ipaadmin_password: "{{ vault_ipaadmin_password }}"
        name: "{{ item.1 }}"
        user: "{{ item.0.name }}"
        state: present
        action: member
      with_subelements:
        - "{{ ipa_users }}"
        - groups
        - skip_missing: true
      loop_control:
        label: "{{ item.0.name }} -> {{ item.1 }}"
