# Parametres DNS
ipaserver_domain: amont.ans.local
ipaserver_realm: AMONT.ANS.LOCAL
ipaserver_setup_dns: yes
ipaserver_auto_reverse: yes
ipaserver_forwarders: ['213.186.33.99']

# Configuration Host & IP
ipa_server_fqdn: infra-amont-freeipa01.amont.ans.local
ipa_server_ip: 10.12.90.13

# Réseaux pour les zones DNS inverses
ipa_reverse_zones:
  - 10.12.90.0/24
  - 10.12.52.0/24
  - 10.12.70.0/24
  - 10.12.30.0/24
